export const ADD_ENGREDIENT = 'ADD_ENGREDIENT'
export const REMOVE_ENGREDIENT = 'REMOVE_ENGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

